<style>
        .footer {
            background-image: linear-gradient(to bottom right, #57998b, #345874);
            color: #ffffff;
            padding: 20px 0;
            text-align: center;
            width: 100%;
            position: fixed;
            bottom: 0;
        }

        .footer .container {
            max-width: 1140px; /* Adjust as needed */
            margin: 0 auto;
        }

        .ft-list {
            list-style-type: none;
            column-count: 2;
            width: 100%;
            max-width: 420px; /* Adjust as needed */
            margin: 0 auto;
        }

        .ft-list li {
            padding-bottom: 10px;
        }

        .ft-list a {
            color: #ffffff;
            text-decoration: none;
        }

        .ft-list a:hover {
            text-decoration: underline;
        }

        .ft-logos {
            width: 224px;
            margin-bottom: 25px;
        }
</style>

<div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4 order-md-2">

                    </div>
                </div>
                <div class="col order-md-1">

                </div>
            </div>
        </div>
    </div>
</body>
</html>